name: Build & Generate Provenance
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    outputs:
      hashes: ${{ steps.hash.outputs.base64 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Archive web application
        run: |
          mkdir -p dist
          zip -r dist/mybinary.zip .

      - name: Generate base64-encoded SHA256 subject
        id: hash
        run: |
          mkdir -p dist
          zip -r dist/mybinary.zip .
          HASH=$(sha256sum dist/mybinary.zip | cut -d ' ' -f 1)
          cat <<EOF > subjects.json
          [
            {
              "name": "dist/mybinary.zip",
              "digest": {
                "sha256": "$HASH"
              }
            }
          ]
          EOF
          base64 -w0 subjects.json > subjects.b64
          echo "base64=$(cat subjects.b64)" >> $GITHUB_OUTPUT

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: mybinary
          path: dist/mybinary.zip          

  provenance:
    needs: [build]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    with:
      base64-subjects: "${{ needs.build.outputs.hashes }}"
      upload-assets: false
      provenance-name: provenance.intoto.jsonl         